from core.feature_extractor.base_extractor import BaseExtractor, TimeSegment
from core.feature_extractor.pause_extractor import PauseExtractor
from core.feature_extractor.speed_extractor import SpeedExtractor
from core.feature_extractor.volume_extractor import VolumeExtractor